version: '3'

services:

   ask-ldapserver:
      build: ./ldapserver
      networks:
         - bartinet
      ports:
         - '8080:8080'

   ask-ticket-sender:
      build:
         context: ./ticket-sender/ticket-sender
         dockerfile: Dockerfile
      volumes:
         - './ticket-sender/ticket-sender:/app'
         - '/app/node_modules'
      environment:
         - CHOKIDAR_USEPOOLING=true
      networks:
         - bartinet
      ports:
         - '3000:3000'
      
   ask-backend:
      build: ./ticket-sender/ticket-sender/backend
      networks:
         - bartinet
      ports:
         - '5000:5000'

networks:
   bartinet:
      driver: bridge

